# Generated by Django 2.2.6 on 2020-01-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todotext',
            new_name='text',
        ),
    ]
